In [6]:
from pyecharts_exporter import display_chart, get_chart_urls

In [1]:
from pyecharts import options as opts
from pyecharts.charts import Timeline, Bar, Pie
import pandas as pd

#导入数据
df = pd.read_csv('data/国内生产总值.csv',encoding='gbk')
df

,指标,2020年,2019年,2018年,2017年,2016年,2015年,2014年,2013年,2012年,2011年
0,国民总收入(亿元),1009151.0,984179.0,914327.1,831381.2,743408.3,686255.7,644380.2,588141.2,537329.0,483392.8
1,国内生产总值(亿元),1015986.2,986515.2,919281.1,832035.9,746395.1,688858.2,643563.1,592963.2,538580.0,487940.2
2,第一产业增加值(亿元),77754.1,70473.6,64745.2,62099.5,60139.2,57774.6,55626.3,53028.1,49084.6,44781.5
3,第二产业增加值(亿元),384255.3,380670.6,364835.2,331580.5,295427.8,281338.9,277282.8,261951.6,244639.1,227035.1
4,第三产业增加值(亿元),553976.8,535371.0,489700.8,438355.9,390828.1,349744.7,310654.0,277983.5,244856.2,216123.6
5,人均国内生产总值(元),72447.0,70581.0,66006.0,60014.0,54139.0,50237.0,47173.0,43684.0,39874.0,36302.0
6,注：1.1980年以后国民总收入与国内生产总值的差额为来自国外的初次分配收入净额。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2.三次产业分类依据国家统计局2018年修订的《三次产业划分规定》。第一产业是指农、林...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,3.按照我国国内生产总值（GDP）数据修订制度和国际通行作法，在第四次全国经济普查后，...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,数据来源：国家统计局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
#获取数据
lable = [2016,2017,2018,2019,2020]
df1 = df.iloc[1:5,[5,4,3,2,1]]
df1

      2016年     2017年     2018年     2019年      2020年
1  746395.1  832035.9  919281.1  986515.2  1015986.2
2   60139.2   62099.5   64745.2   70473.6    77754.1
3  295427.8  331580.5  364835.2  380670.6   384255.3
4  390828.1  438355.9  489700.8  535371.0   553976.8

In [3]:
data0 = list(df1.iloc[0])  #2016-2020国内生产总值(亿元)
data1 = list(df1.iloc[1])  #2016-2020第一产业增加值(亿元)
data2 = list(df1.iloc[2])  #2016-2020第二产业增加值(亿元)
data3 = list(df1.iloc[3])  #2016-2020第三产业增加值(亿元)
data1

[60139.2, 62099.5, 64745.2, 70473.6, 77754.1]

In [4]:
rate1 = list(round(df1.iloc[1]/df1.iloc[0]*100,2)) #round(x,n)方法返回浮点数x的四舍五入值。
rate2 = list(round(df1.iloc[2]/df1.iloc[0]*100,2))
rate3 = list(round(df1.iloc[3]/df1.iloc[0]*100,2))
rate1

[8.06, 7.46, 7.04, 7.14, 7.65]

In [5]:
#定义函数
def get_year_overlap_chart(year: int) :
    # 绘制多数据系列柱形图
    bar = (
        Bar(opts.InitOpts(width="1500px", height="580px"))
        .add_xaxis(lable)
        .add_yaxis("国内生产总值", data0)
        .add_yaxis("第一产业增加值", data1)
        .add_yaxis("第二产业增加值", data2)
        .add_yaxis("第三产业增加值", data3)
        .set_global_opts(
            title_opts=opts.TitleOpts(
            title="5年期间国内生产总值及第一产业、第二产业、第三产业增加值情况",
            subtitle="单位：亿元 ",
            pos_left='left'),
            # 添加脚注
            graphic_opts=opts.GraphicGroup(
                graphic_item=opts.GraphicItem(left='4%', bottom='3%'),
                children=[
                    opts.GraphicText(graphic_textstyle_opts=
                                     opts.GraphicTextStyleOpts(text='数据来源：国家统计局',
                                     font="14px Microsoft YaHei"))]
            ),
           # 添加图例
            legend_opts=opts.LegendOpts(selected_mode='multiple',
                                          orient='vertical',
                                          is_show=True,
                                          pos_right='5',
                                          pos_bottom='55%'))
        )
    #绘制饼图
    pie = (
        Pie()
        .add(
            series_name="占比",
            data_pair=[
                ["第一产业增加值占比", rate1[year]],
                ["第二产业增加值占比", rate2[year]],
                ["第三产业增加值占比", rate3[year]]
            ],
            center=["38%", "18%"],    #饼图中心点在画布的位置
            radius="18%",
            is_clockwise=False)
        .set_global_opts(legend_opts=opts.LegendOpts(is_show=False))
        .set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{c}%"))
    )   
    return bar.overlap(pie)


# 创建时间线轮播多图
timeline = Timeline(init_opts=
                    opts.InitOpts(width="900px", height="600px"))  #初始化配置

for y in range(5):
    print(y)
    timeline.add(get_year_overlap_chart(year=y), time_point=str(y))  #添加图表实例和时间点
                                                                     #这里图表实例是自定义函数
timeline.add_schema(is_auto_play=True, play_interval=2000);  #timeline.add_schema函数可设置坐标轴类型、时间轴类型等
#timeline.render("d:/html/task7-1.html")

0
1
2
3
4

In [7]:
display_chart(timeline)

In [8]:
!jupyter nbconvert --to html 3-1组合图国内生产总值.ipynb

[NbConvertApp] Converting notebook 3-1组合图国内生产总值.ipynb to html
[NbConvertApp] Writing 407166 bytes to 3-1组合图国内生产总值.html