In [6]:
from pyecharts_exporter import display_chart

###

In [7]:
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.faker import Faker

c = (
    Geo()
    .add_schema(maptype="china")
    .add("geo", 
         [list(z) for z in zip(Faker.provinces, Faker.values())]
        )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(is_piecewise=True),
        title_opts=opts.TitleOpts(title="Geo-VisualMap（分段型）"),
    )
    
)

display_chart(c)

In [8]:
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.faker import Faker
from pyecharts.globals import ChartType 

c = (
    Geo()
    .add_schema(maptype="china")
    .add("geo", 
         [list(z) for z in zip(Faker.provinces, Faker.values())],
        type_=ChartType.EFFECT_SCATTER,
        )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(), title_opts=opts.TitleOpts(title="Geo-涟漪散点图示例")
    )
    
)

display_chart(c)

In [4]:
from pyecharts import options as opts
from pyecharts.charts import Geo
from pyecharts.faker import Faker

c = (
    Geo()
    .add_schema(maptype="china")
    .add("geo", 
         [list(z) for z in zip(Faker.provinces, Faker.values())],
        type_=ChartType.HEATMAP,
        )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(
        visualmap_opts=opts.VisualMapOpts(), title_opts=opts.TitleOpts(title="Geo-热力图示例")
    )
    
)

display_chart(c)

## 实例1 全国主要城市航班流动图为例（虚拟数据）

In [9]:
from pyecharts import options as opts 
from pyecharts.charts import Geo 
from pyecharts.globals import ChartType, SymbolType

c = (
    Geo()
    .add_schema(maptype="china")
    .add( "",
        [ ("哈尔滨", 66), ("重庆", 88), ("上海", 100), ("乌鲁木齐", 30),("北京", 30),("兰州",170)],
        type_=ChartType.EFFECT_SCATTER,
        color="green",
    )
    .add(
        "geo",
        [("北京", "兰州"),( "兰州","北京"), ("重庆", "上海"),("哈尔滨", "重庆"),("乌鲁木齐", "哈尔滨")],
        type_=ChartType.LINES,
        effect_opts=opts.EffectOpts(symbol=SymbolType.ARROW, symbol_size=6, color="blue"),# 设置特效图形为箭头，特效图形的大小、颜色
        linestyle_opts=opts.LineStyleOpts(curve=0.2),  #设置线条样式 curve 参数设置为 0.2，表示线条将有轻微的曲线效果。
    )
    .set_series_opts(label_opts=opts.LabelOpts(is_show=False))
    .set_global_opts(title_opts=opts.TitleOpts(title="主要城市航班路线和数量"))
)

display_chart(c)

## 实例2 广东人口分布图

In [13]:
import re
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts 

data=pd.read_excel('c:/dataset/03-07.xls')
data

,3-7 各市年末常住人口数,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,Permanent Population at Year-end by City,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,单位：万人,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(10000 persons)
3,市 别,City,2000.00,2005.00,2010.0000,2016.00,2017.00,2018.00,2019.00,2020.00,2021.00,2022
4,全 省,Provincial Total,8650.03,9194.00,10440.9400,11908.00,12141.00,12348.00,12489.00,12624.00,12684.00,12656.8
5,广 州,Guangzhou,994.80,949.68,1270.9585,1678.38,1746.27,1798.13,1831.21,1874.03,1881.06,1873.41
6,深 圳,Shenzhen,701.24,827.75,1043.7600,1501.51,1587.31,1666.12,1710.40,1763.38,1768.16,1766.18
7,珠 海,Zhuhai,123.65,141.57,156.1569,195.98,207.02,220.90,233.18,244.96,246.67,247.72
8,汕 头,Shantou,467.78,494.45,539.6199,546.46,547.51,548.59,549.31,550.37,553.04,554.19
9,佛 山,Foshan,534.05,580.03,719.9107,874.77,899.99,926.04,943.14,951.88,961.26,955.23
10,韶 关,Shaoguan,273.65,292.26,283.0198,283.95,284.47,284.78,285.07,285.53,286.01,286.18
11,河 源,Heyuan,226.78,278.24,295.8202,289.13,287.38,285.89,284.83,283.56,284.09,284.17
12,梅 州,Meizhou,380.52,411.84,424.4648,403.76,400.02,395.51,391.96,387.10,387.69,385.8
13,惠 州,Huizhou,321.80,370.69,460.1147,562.73,572.22,584.72,597.23,605.72,606.60,605.02
14,汕 尾,Shanwei,245.71,279.87,287.3400,274.87,272.55,270.50,268.85,266.94,268.69,268.26
15,东 莞,Dongguan,644.84,656.07,822.4772,1016.58,1038.22,1043.77,1045.50,1048.36,1053.68,1043.7
16,中 山,Zhongshan,236.47,243.46,312.2711,407.69,418.04,428.82,438.73,443.11,446.69,443.11
17,江 门,Jiangmen,395.24,410.29,445.0786,461.85,465.12,470.38,475.32,480.41,483.51,482.22
18,阳 江,Yangjiang,217.20,232.14,242.5331,254.02,255.73,257.26,259.09,260.59,262.07,262.22
19,湛 江,Zhanjiang,603.43,668.95,700.3768,698.49,698.30,698.23,698.16,698.07,703.09,703.54
20,茂 名,Maoming,524.82,584.04,582.6397,593.72,598.52,605.95,612.26,618.00,621.97,623.82
21,肇 庆,Zhaoqing,337.69,367.60,392.2224,401.75,403.88,406.58,409.24,411.69,412.97,412.84
22,清 远,Qingyuan,314.98,359.37,370.3848,388.32,390.66,393.12,395.48,397.40,398.28,398.57
23,潮 州,Chaozhou,240.44,252.01,267.2143,259.46,259.09,258.81,258.29,256.66,257.46,257.56
24,揭 阳,Jieyang,524.61,559.69,588.3043,576.60,570.62,565.81,563.42,557.87,561.68,563.41
25,云 浮,Yunfu,215.49,233.99,236.2942,237.98,238.07,238.09,238.33,238.37,239.33,239.65
26,按经济区域分,By Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,珠 三 角,Pearl River Delta,4289.78,4547.14,5622.9500,7101.24,7338.07,7545.46,7683.95,7823.54,7860.60,7829.43
28,东 翼,Eastern Region,1478.54,1586.02,1682.4700,1657.39,1649.77,1643.71,1639.87,1631.84,1640.87,1643.42
29,西 翼,Western Region,1345.45,1485.13,1525.5500,1546.23,1552.55,1561.44,1569.51,1576.66,1587.13,1589.58
30,山 区,Mountainous Region,1411.42,1575.70,1609.9700,1603.14,1600.60,1597.39,1595.67,1591.96,1595.40,1594.37
31,注：1.2000年全省数据含根据普查误差率推算的漏登人口。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,2.2006-2009年年末常住人口根据2010年第六次全国人口普查结果平滑调整。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,3.2010年开始，深圳市包含深汕合作区人口。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,4.2011-2019年年末常住人口根据2020年第七次全国人口普查结果平滑调整。,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Note: a)Data for the permanent population of 2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,b)Data for the permanent population ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,c)Data for the 2010 permanent popula...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,d)Figures of permanent population at...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Population Census in 2020.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
import re
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts 

data = pd.read_excel('c:/dataset/03-07.xls')
city = data.iloc[5:26,0].apply(lambda x: re.sub(r'\s+', '', x) +'市') # re.sub(r'\s+', '', x) —— 使用正则表达式 \s+ 匹配一个或多个空白字符（空格、制表符、换行等），将它们替换为空字符串，即去除所有空白。
population = data.iloc[5:26,11]
z3 = [list(i) for i in zip(city,population)]
z3

[['广州市', 1873.41],
 ['深圳市', 1766.18],
 ['珠海市', 247.72],
 ['汕头市', 554.19],
 ['佛山市', 955.23],
 ['韶关市', 286.18],
 ['河源市', 284.17],
 ['梅州市', 385.8],
 ['惠州市', 605.02],
 ['汕尾市', 268.26],
 ['东莞市', 1043.7],
 ['中山市', 443.11],
 ['江门市', 482.22],
 ['阳江市', 262.22],
 ['湛江市', 703.54],
 ['茂名市', 623.82],
 ['肇庆市', 412.84],
 ['清远市', 398.57],
 ['潮州市', 257.56],
 ['揭阳市', 563.41],
 ['云浮市', 239.65]]

In [15]:
map=(
    Map(init_opts=opts.InitOpts(width="1200px",height='600px'))
    .add('广东人口', data_pair=z3, maptype='广东', is_map_symbol_show=False)
    .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
    .set_global_opts(title_opts=opts.TitleOpts(title='广东人口分布图', subtitle='数据来源：广东统计年鉴'),
                     visualmap_opts=opts.VisualMapOpts(max_=2000,is_piecewise=True,
                                                       range_color=['lightskyblue','yellow','orangered'])
                    )
)

In [16]:
map.load_javascript()

In [17]:
map.render_notebook()

In [18]:

geo=(
    Geo(init_opts=opts.InitOpts(width="1200px",height='600px'))
    .add_schema(maptype='广东',itemstyle_opts=opts.ItemStyleOpts(color='#333333',border_color='#FFFF22'))  # 设置项目样式
    .add('广东人口',z3,label_opts=opts.LabelOpts(is_show=False),type_=ChartType.EFFECT_SCATTER)
    .set_global_opts(title_opts=opts.TitleOpts(title='广东人口分布图',subtitle='数据来源：广东统计年鉴'),
                     visualmap_opts=opts.VisualMapOpts(max_=2000,is_piecewise=True,
                                                       range_color=['lightskyblue','yellow','orangered'])
                    )
)
geo.load_javascript()

In [19]:
geo.render_notebook()

In [20]:
import pandas as pd
from pyecharts.charts import Map
from pyecharts import options as opts 
from pyecharts.globals import ChartType

data = pd.read_excel('c:/dataset/02-06.xls',sheet_name='Sheet1')
city = data.iloc[9:-1,0].str.strip(' ')  # 对 Series 中的每个字符串元素：strip(' ') 会删除字符串开头和结尾的空格字符，注意：它不会删除字符串中间的空格，也不会删除其他空白字符（如 \t、\n）。
population = data.iloc[9:-1,3]
z3 = [list(i) for i in zip(city,population)]

data

,2-6 各区常住人口和城镇人口,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Permanent Population and Urban Population by R...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,单位：万人(10 000 persons)
3,地 区,Region,常住人口,NaN,城镇人口,NaN
4,NaN,NaN,Permanent Population,NaN,Urban Population,NaN
5,NaN,NaN,2021,2022.00,2021,2022
6,NaN,NaN,NaN,NaN,NaN,NaN
7,全 市 总 计,Total,1373,1363.00,1165.4,1160.06
8,# 中心城区,Central Districts,395.85,391.02,395.85,391.02
9,和平区,Heping District,35.45,34.44,35.45,34.44
10,河东区,Hedong District,84.89,83.96,84.89,83.96
11,河西区,Hexi District,80.9,80.37,80.9,80.37
12,南开区,Nankai District,87.73,86.43,87.73,86.43
13,河北区,Hebei District,63.98,62.94,63.98,62.94
14,红桥区,Hongqiao District,42.9,42.88,42.9,42.88
15,东丽区,Dongli District,84.66,83.89,84.66,83.89
16,西青区,Xiqing District,118.88,118.62,113.15,113.41
17,津南区,Jinnan District,92.71,92.43,92.71,92.43
18,北辰区,Beichen District,94.67,94.15,86.42,86.55
19,武清区,Wuqing District,113.84,113.94,63.13,63.84
20,宝坻区,Baodi District,71.71,71.06,30.91,30.76
21,滨海新区,Binhai New Area,204.57,202.38,196.93,195.83
22,宁河区,Ninghe District,38.96,38.72,18.65,18.68
23,静海区,Jinghai District,78.07,77.92,44.64,44.95
24,蓟州区,Jizhou District,79.08,78.87,38.35,38.7
25,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
map=(
    Map(init_opts=opts.InitOpts(width="1200px",height='600px'))
    .add('天津人口',data_pair=z3,maptype='天津',is_map_symbol_show=False)
    .set_series_opts(label_opts=opts.LabelOpts(is_show=True))
    .set_global_opts(title_opts=opts.TitleOpts(title='天津人口分布图',subtitle='数据来源：天津统计年鉴'),
                     visualmap_opts=opts.VisualMapOpts(max_=210,is_piecewise=True,
                                                       range_color=['lightskyblue','yellow','orangered'])
                    )
)
map.load_javascript()

In [22]:
map.render_notebook()