In [1]:
from pyecharts_exporter import display_chart

## 3.6.1  桑基图

In [2]:
from pyecharts import options as opts
from pyecharts.charts import Sankey

nodes = [                      #定义节点
    {"name": "category1"},
    {"name": "category2"},
    {"name": "category3"},
    {"name": "category4"},
    {"name": "category5"},
    {"name": "category6"},
]

links = [                        #定义节点中间的链接，即关系
    {"source": "category1", "target": "category2", "value": 10},
    {"source": "category2", "target": "category3", "value": 15},
    {"source": "category3", "target": "category4", "value": 20},
    {"source": "category5", "target": "category6", "value": 25},
]
c = (
    Sankey()
    .add(
        "sankey",
        nodes,
        links,
        linestyle_opt=opts.LineStyleOpts(
            opacity=0.2,   # 线条透明度
            curve=0.5,     # 线条弯曲程度
            color="source"),   # 线条颜色跟随源节点的颜色
        label_opts=opts.LabelOpts(position="right"),  # 标签显示在右边
    )
    .set_global_opts(title_opts=opts.TitleOpts(title="Sankey-基本示例"))
)

display_chart(c)

In [3]:
# 导入相关库	
import pandas as pd	
from pyecharts.charts import Page, Sankey
from pyecharts import options as opts
 

# 读取csv文件
df = pd.read_excel(r'data/我的生活支出一览.xlsx')
df

    支出类别  支出项目    金额
0    牛仔裤    服饰   500
1     毛衣    服饰   800
2     短袖    服饰   400
3     皮鞋    服饰  1000
4     衬衫    服饰   700
5     地铁    交通   200
6     火车    交通   650
7     飞机    交通  2000
8     上网    娱乐   300
9    KTV    娱乐   500
10   游乐园    娱乐   300
11   电影票    娱乐   600
12    外卖    餐饮  1200
13    奶茶    餐饮   200
14    图书    教育   700
15  付费课程    教育  1500
16   感冒药    医疗   100
17    拔牙    医疗  1200
18    健身    体育  1500
19    滑雪    体育   300
20    瑜伽    体育   800
21    服饰  衣食住行  3400
22    交通  衣食住行  2850
23    餐饮  衣食住行  1400
24    娱乐  娱乐教育  1700
25    教育  娱乐教育  2200
26    医疗  医疗体育  1300
27    体育  医疗体育  1800
28  衣食住行   总支出  7650
29  娱乐教育   总支出  3900
30  医疗体育   总支出  3100

In [4]:
# 导入相关库	
import pandas as pd	
from pyecharts.charts import Page, Sankey
from pyecharts import options as opts

# 定义nodes
nodes = [
    {'name': '总支出'},
    {'name': '牛仔裤'},
    {'name': '毛衣'},
    {'name': '短袖'},
    {'name': '皮鞋'},
    {'name': '衬衫'},
    {'name': '地铁'},
    {'name': '火车'},
    {'name': '飞机'},
    {'name': '上网'},
    {'name': 'KTV'},
    {'name': '游乐园'},
    {'name': '电影票'},
    {'name': '外卖'},
    {'name': '奶茶'},
    {'name': '图书'},
    {'name': '付费课程'},
    {'name': '感冒药'},
    {'name': '拔牙'},
    {'name': '健身'},
    {'name': '滑雪'},
    {'name': '瑜伽'},
    {'name': '服饰'},
    {'name': '交通'},
    {'name': '餐饮'},
    {'name': '娱乐'},
    {'name': '教育'},
    {'name': '医疗'},
    {'name': '体育'},
    {'name': '衣食住行'},
    {'name': '娱乐教育'},
    {'name': '医疗体育'}
]

# 定义links
links = [
    {'source': '牛仔裤', 'target': '服饰', 'value': 500},
    {'source': '毛衣', 'target': '服饰', 'value': 800},
    {'source': '短袖', 'target': '服饰', 'value': 400},
    {'source': '皮鞋', 'target': '服饰', 'value': 1000},
    {'source': '衬衫', 'target': '服饰', 'value': 700},
    {'source': '地铁', 'target': '交通', 'value': 200},
    {'source': '火车', 'target': '交通', 'value': 650},
    {'source': '飞机', 'target': '交通', 'value': 2000},
    {'source': '上网', 'target': '娱乐', 'value': 300},
    {'source': 'KTV', 'target': '娱乐', 'value': 500},
    {'source': '游乐园', 'target': '娱乐', 'value': 300},
    {'source': '电影票', 'target': '娱乐', 'value': 600},
    {'source': '外卖', 'target': '餐饮', 'value': 1200},
    {'source': '奶茶', 'target': '餐饮', 'value': 200},
    {'source': '图书', 'target': '教育', 'value': 700},
    {'source': '付费课程', 'target': '教育', 'value': 1500},
    {'source': '感冒药', 'target': '医疗', 'value': 100},
    {'source': '拔牙', 'target': '医疗', 'value': 1200},
    {'source': '健身', 'target': '体育', 'value': 1500},
    {'source': '滑雪', 'target': '体育', 'value': 300},
    {'source': '瑜伽', 'target': '体育', 'value': 800},
    {'source': '服饰', 'target': '衣食住行', 'value': 3400},
    {'source': '交通', 'target': '衣食住行', 'value': 2850},
    {'source': '餐饮', 'target': '衣食住行', 'value': 1400},
    {'source': '娱乐', 'target': '娱乐教育', 'value': 1700},
    {'source': '教育', 'target': '娱乐教育', 'value': 2200},
    {'source': '医疗', 'target': '医疗体育', 'value': 1300},
    {'source': '体育', 'target': '医疗体育', 'value': 1800},
    {'source': '衣食住行', 'target': '总支出', 'value': 7650},
    {'source': '娱乐教育', 'target': '总支出', 'value': 3900},
    {'source': '医疗体育', 'target': '总支出', 'value': 3100}
]

# pyecharts 所有方法均支持链式调用
c = (
    Sankey()
    .add(
        "费用/元",
        nodes,
        links,
        linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source",type_="dotted"),
        label_opts=opts.LabelOpts(position="right",),
        )
    .set_global_opts(title_opts=opts.TitleOpts(title="我的生活支出一览"))
)

display_chart(c)

In [5]:
import pandas as pd
from pyecharts.charts import Sankey
from pyecharts import options as opts

# 读取Excel文件
data = pd.read_excel(r'data/我的生活支出一览.xlsx')

# 假设Excel文件中有三列，列名分别是'支出类别'，'支出项目'和'金额'
category_col = '支出类别'
item_col = '支出项目'
value_col = '金额'

# 生成nodes
nodes = [{'name': '总支出'}]
for category in data[category_col].unique():
    nodes.append({'name': category})

# 生成links
links = []
for index, row in data.iterrows():
    links.append({
        'source': row[category_col],
        'target': row[item_col],
        'value': row[value_col]
    })
    
# 创建桑基图
sankey = (
    Sankey()
    .add(
        "费用/元",
        nodes,
        links,
        linestyle_opt=opts.LineStyleOpts(opacity=0.2, curve=0.5, color="source", type_="dotted"),
        label_opts=opts.LabelOpts(position="right"),
    )
    .set_global_opts(title_opts=opts.TitleOpts(title="我的生活支出一览"))
)


display_chart(sankey)

## 3.6.2 网络图

In [6]:
from pyecharts import options as opts
from pyecharts.charts import Graph

nodes_data = [
    opts.GraphNode(name="结点1", symbol_size=10),
    opts.GraphNode(name="结点2", symbol_size=20),
    opts.GraphNode(name="结点3", symbol_size=30),
    opts.GraphNode(name="结点4", symbol_size=40),
    opts.GraphNode(name="结点5", symbol_size=50),
    opts.GraphNode(name="结点6", symbol_size=60),
]
links_data = [
    opts.GraphLink(source="结点1", target="结点2", value=2),
    opts.GraphLink(source="结点2", target="结点3", value=3),
    opts.GraphLink(source="结点3", target="结点4", value=4),
    opts.GraphLink(source="结点4", target="结点5", value=5),
    opts.GraphLink(source="结点5", target="结点6", value=6),
    opts.GraphLink(source="结点6", target="结点1", value=7),
]
c = (
    Graph()
    .add(
        "",
        nodes_data,
        links_data,
        repulsion=4000,   #repulsion 参数设置了节点之间的斥力
        edge_label=opts.LabelOpts(
            is_show=True, position="middle", formatter="{b} 的数据 {c}"   #edge_label 设置了边的标签样式和显示位置
        ),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Graph-GraphNode-GraphLink-WithEdgeLabel")
    )
    #.render("graph_with_edge_options.html")
)

display_chart(c)

In [7]:
from pyecharts import options as opts
from pyecharts.charts import Graph

nodes_data = [
    opts.GraphNode(name="A", symbol_size=20),
    opts.GraphNode(name="B", symbol_size=30),
    opts.GraphNode(name="C", symbol_size=40),
    opts.GraphNode(name="D", symbol_size=50),
    opts.GraphNode(name="E", symbol_size=50),
    opts.GraphNode(name="F", symbol_size=50),
]
links_data = [
    opts.GraphLink(source="A", target="B", value=2),
    opts.GraphLink(source="B", target="C", value=3),
    opts.GraphLink(source="C", target="D", value=4),
    opts.GraphLink(source="D", target="E", value=5),
    opts.GraphLink(source="E", target="F", value=6),
    opts.GraphLink(source="F", target="C", value=7),   #没有首尾相连，F节点连到C
]
c = (
    Graph()
    .add(
        "",
        nodes_data,
        links_data,
        repulsion=4000,   #repulsion 参数设置了节点之间的斥力
        edge_label=opts.LabelOpts(
            is_show=True, position="middle", formatter="{c}"   #edge_label 设置了边的标签样式和显示位置
        ),
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Graph-GraphNode-GraphLink-WithEdgeLabel")
    )
    #.render("graph_with_edge_options.html")
)

display_chart(c)

## 网络图实例 海绵宝宝动画片角色关系图

In [8]:
from pyecharts.charts import Graph

nodes_data = [
    opts.GraphNode(name="海绵宝宝", symbol_size=80  ),
    opts.GraphNode(name="派大星", symbol_size=45  ),
    opts.GraphNode(name="小蜗", symbol_size=45   ),
    opts.GraphNode(name="蟹老板", symbol_size=60   ),
    opts.GraphNode(name="章鱼哥", symbol_size=45   ),
    opts.GraphNode(name="泡芙老师", symbol_size=60  ),
    opts.GraphNode(name="痞老板", symbol_size=60   ),
    opts.GraphNode(name="拉里", symbol_size=45    ),
    opts.GraphNode(name="射线恶魔", symbol_size=50  ),
    opts.GraphNode(name="珍珍", symbol_size=45   ),

]
links_data = [
    opts.GraphLink(source="海绵宝宝", target="派大星", value='好友',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="小蜗", value='好友',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="章鱼哥", value='邻居',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="蟹老板", value='雇佣',symbol = ['arrow',None]),
    opts.GraphLink(source="海绵宝宝", target="泡芙老师", value='师徒',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="痞老板", value='敌人',symbol = ['arrow','arrow']),
    opts.GraphLink(source="蟹老板", target="章鱼哥", value='雇佣',symbol = [None,'arrow']),
    opts.GraphLink(source="蟹老板", target="痞老板", value='敌人',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="拉里", value='崇拜',symbol=[None,'arrow']),
    opts.GraphLink(source="海绵宝宝", target="射线恶魔", value='亦敌亦友',symbol = ['arrow','arrow']),
    opts.GraphLink(source="海绵宝宝", target="珍珍", value='好友',symbol = ['arrow','arrow']),
    opts.GraphLink(source="蟹老板", target="珍珍", value='父女',symbol=[None,'arrow']),
]
c = (
    Graph(init_opts=opts.InitOpts(width='1470px',height='730px'))
    .add(
        "",
        nodes_data,
        links = links_data,
        repulsion=5000,       #repulsion 参数设置了节点之间的斥力
        is_draggable = True,     #is_draggable 允许用户拖动节点。
        edge_label=opts.LabelOpts(
            is_show=True, position="middle", formatter="关系:{c}",                #edge_label 设置了边的标签样式和显示位置
        ),
        label_opts = opts.LabelOpts(color='white',font_size=12)
    )
    .set_global_opts(title_opts=opts.TitleOpts(title="《海绵宝宝》动画片角色关系图"))
)

display_chart(c)

## 网络图实例 微博转发关系图
`weibo.json`无

In [17]:
import json
from pyecharts import options as opts
from pyecharts.charts import Graph
import pandas as pd

with open(r"data/weibo.json", "r", encoding="utf-8") as f:
    j = json.load(f)
nodes, links, categories, *_ = j
df_nodes=pd.DataFrame(nodes)
df_nodes.head()

,name,symbolSize,draggable,value,category,label
0,,5,False,1,,{'normal': {'show': 'True'}}
1,Camel3942,5,False,1,Camel3942,{'normal': {'show': 'True'}}
2,Christinez,13,False,7,Christinez,{'normal': {'show': 'True'}}
3,JoannaBlue,5,False,1,JoannaBlue,{'normal': {'show': 'True'}}
4,Michael-Cheung-,5,False,1,Michael-Cheung-,{'normal': {'show': 'True'}}

In [18]:
df_links=pd.DataFrame(links)
df_links.head()

   source       target
0    新浪体育       阿根廷人小马
1    新浪体育  Beijingold4
2    麻黑浮云        X一块红布
3  胖猪猪呼呼睡         麻黑浮云
4    麻黑浮云       胖猪猪呼呼睡

In [19]:
df_categories=pd.DataFrame(categories)
df_categories.head()

              name
0
1        Camel3942
2       Christinez
3       JoannaBlue
4  Michael-Cheung-

In [20]:
g = (
    Graph()
    .add(
        "",
        nodes,
        links,
        categories,
        repulsion=50,
        linestyle_opts=opts.LineStyleOpts(curve=0.2),
        label_opts=opts.LabelOpts(is_show=False),
    )
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        title_opts=opts.TitleOpts(title="微博转发关系图"),
    )
)

display_chart(g)

## 3.6.3 环形弧长链接图

## 环形图实例-《悲惨世界》人物关系图
该图基于维克多·雨果的小说《悲惨世界》中的人物关系数据，展示了小说中各个角色之间的联系，例如谁与谁相遇过，他们之间的关系如何。

In [12]:
import json
from pyecharts import options as opts
from pyecharts.charts import Graph

with open("data/les-miserables.json", "r", encoding="utf-8") as f:
    j = json.load(f)
    nodes = j["nodes"]
    links = j["links"]
    categories = j["categories"]
print(nodes[:2])
print(links[:5])
print(categories)

c = (
    Graph(init_opts=opts.InitOpts(width="1000px", height="600px"))
    .add(
        "",
        nodes=nodes,
        links=links,
        categories=categories,
        layout="circular",          #提供了其他几种布局选项，如 "circular"（环形）、"none"（无布局，自定义位置）、"force"（力导向布局）
        is_rotate_label=True,    #is_rotate_label 设置为 True 表示标签旋转
        linestyle_opts=opts.LineStyleOpts(color="source", curve=0.3),  #设置了边的样式。
        label_opts=opts.LabelOpts(position="right"),                   #设置了标签的样式。
    )
    .set_global_opts(
        title_opts=opts.TitleOpts(title="Graph-Les Miserables"),
        legend_opts=opts.LegendOpts(orient="vertical", pos_left="2%", pos_top="20%"),
    )
)

display_chart(c)

[{'id': '0', 'name': 'Myriel', 'symbolSize': 19.12381, 'x': -266.82776, 'y': 299.6904, 'value': 28.685715, 'category': 0}, {'id': '1', 'name': 'Napoleon', 'symbolSize': 2.6666666666666665, 'x': -418.08344, 'y': 446.8853, 'value': 4, 'category': 0}]
[{'source': '1', 'target': '0'}, {'source': '2', 'target': '0'}, {'source': '3', 'target': '0'}, {'source': '3', 'target': '2'}, {'source': '4', 'target': '0'}]
[{'name': 'A'}, {'name': 'B'}, {'name': 'C'}, {'name': 'D'}, {'name': 'E'}, {'name': 'F'}, {'name': 'G'}, {'name': 'H'}, {'name': 'I'}]