<img src=".\image\实验02-1.png" alt="实验02-1" style="zoom:25%;"/>

<img src=".\image\实验02-2.png" alt="实验02-2" style="zoom:50%;"/>

In [43]:
import pandas as pd
import numpy as np
import chardet

In [44]:
print('1.')
data1 = np.array([('Mayue',3000),
                 ('Lilin',4500),
                 ('Wuyun',8000)])
adf = pd.DataFrame(data1,index = range(1,4),columns=['name','pay'])
adf['pay'] = pd.to_numeric(adf['pay'],errors='coerce')
adf

1.

    name   pay
1  Mayue  3000
2  Lilin  4500
3  Wuyun  8000

In [45]:
# (1) 添加tax列和行索引为5的行
print('1.(1)')
adf['tax'] = [0.05, 0.05, 0.1]
adf.loc[5] = ['Liuxi', 5000, 0.05]
adf

1.(1)

    name   pay   tax
1  Mayue  3000  0.05
2  Lilin  4500  0.05
3  Wuyun  8000  0.10
5  Liuxi  5000  0.05

In [46]:
# (2) 删除行索引为5的行和tax列
print('1.(2)')
adf_del = adf.drop(5).drop('tax', axis=1)
adf

1.(2)

    name   pay   tax
1  Mayue  3000  0.05
2  Lilin  4500  0.05
3  Wuyun  8000  0.10
5  Liuxi  5000  0.05

In [47]:
# (3) 修改tax列和Liuxi的值
print('1.(3)')
adf['tax'] = 0.03
adf.loc[adf['name'] == 'Liuxi', ['pay', 'tax']] = [9800, 0.05]
adf

1.(3)

    name   pay   tax
1  Mayue  3000  0.03
2  Lilin  4500  0.03
3  Wuyun  8000  0.03
5  Liuxi  9800  0.05

In [48]:
# (4) 求工资均值
print('1.(4)')
adf['pay'] = pd.to_numeric(adf['pay'])
mean_pay = adf['pay'].mean()
print(f"平均工资: {mean_pay}")

1.(4)
平均工资: 6325.0

<img src=".\image\实验02-3.png" alt="实验02-3" style="zoom:50%;"/>

In [49]:
# (1) 显示前五行数据
file = './data/分省年度数据.csv'
with open(file, 'rb') as f:
    result = chardet.detect(f.read())
    print(result,'\n')

print('2.(1)前五行数据:')
df = pd.read_csv(file, encoding=result['encoding'])
df.head(5)

{'encoding': 'GB2312', 'confidence': 0.99, 'language': 'Chinese'}

2.(1)前五行数据:

,地区,2019年,2018年,2017年,2016年,2015年,2014年,2013年,2012年,2011年
0,北京市,35445.1,33106.0,29883.0,27041.2,24779.1,22926.0,21134.6,19024.7,17188.8
1,天津市,14055.5,13362.9,12450.6,11477.2,10879.5,10640.6,9945.4,9043.0,8112.5
2,河北省,34978.6,32494.6,30640.8,28474.1,26398.4,25208.9,24259.6,23077.5,21384.7
3,山西省,16961.6,15958.1,14484.3,11946.4,11836.4,12094.7,11987.2,11683.1,10894.4
4,内蒙古自治区,17212.5,16140.8,14898.1,13789.3,12949.0,12158.2,11392.4,10470.1,9458.1

In [50]:
# (2) 列出数据ndim和shape
print(f"2.(2) ndim: {df.ndim}, shape: {df.shape}")

2.(2) ndim: 2, shape: (31, 10)

In [51]:
# (3) 每个省份2011-2019年GDP总和
df['总和'] = df.iloc[:, 1:].sum(axis=1)
print("2.(3) 各省份2011-2019年GDP总和:")
print(df[['地区', '总和']])

2.(3) 各省份2011-2019年GDP总和:
         地区        总和
0       北京市  230528.5
1       天津市   99967.2
2       河北省  246917.2
3       山西省  117846.2
4    内蒙古自治区  118468.5
5       辽宁省  184099.6
6       吉林省   90154.6
7      黑龙江省  107259.6
8       上海市  253487.6
9       江苏省  653062.0
10      浙江省  407224.9
11      安徽省  228401.8
12      福建省  256840.0
13      江西省  157124.3
14      山东省  494394.1
15      河南省  347299.9
16      湖北省  284536.5
17      湖南省  258992.7
18      广东省  697233.3
19      广西省  137209.7
20      海南省   34381.5
21      重庆市  148732.4
22      四川省  291034.1
23      贵州省   97565.3
24      云南省  141407.1
25      西藏省    9900.8
26      陕西省  167778.6
27      甘肃省   60366.5
28      青海省   18883.3
29  宁夏回族自治区   24684.2
30      新疆省   88105.0

In [52]:
# (4) 2019年全国各省份GDP总值
gdp_2019_total = df['2019年'].sum()
print(f"2.(4）2019年全国各省份GDP总值: {gdp_2019_total}")

2.(4）2019年全国各省份GDP总值: 982320.5000000001

In [53]:
# (5) 各省份2011-2019年GDP最小值
df['最小值'] = df.iloc[:, 1:-1].min(axis=1)
print("2.(5）各省份2011-2019年GDP最小值:")
print(df[['地区', '最小值']])

2.(5）各省份2011-2019年GDP最小值:
         地区      最小值
0       北京市  17188.8
1       天津市   8112.5
2       河北省  21384.7
3       山西省  10894.4
4    内蒙古自治区   9458.1
5       辽宁省  16354.9
6       吉林省   7734.6
7      黑龙江省   9935.0
8       上海市  20009.7
9       江苏省  48839.2
10      浙江省  31854.8
11      安徽省  16284.9
12      福建省  17917.7
13      江西省  11584.5
14      山东省  39064.9
15      河南省  26318.7
16      湖北省  19942.5
17      湖南省  18915.0
18      广东省  53072.8
19      广西省  10299.9
20      海南省   2463.8
21      重庆市  10161.2
22      四川省  21050.9
23      贵州省   5615.6
24      云南省   9523.1
25      西藏省    611.5
26      陕西省  12175.1
27      甘肃省   4816.9
28      青海省   1370.4
29  宁夏回族自治区   1931.8
30      新疆省   6532.0

In [54]:
# (6) 2018年GDP值最大的省
max_2018_province = df.loc[df['2018年'].idxmax(), '地区']
max_2018_value = df['2018年'].max()
print(f"2.(6）2018年GDP值最大的省: {max_2018_province} {max_2018_value}")

2.(6）2018年GDP值最大的省: 广东省 99945.2

In [55]:
# (7) 湖南省2011-2019年的GDP均值
hunan_mean = df[df['地区'] == '湖南省'].iloc[:, 1:-2].mean(axis=1).values[0]
print(f"2.(7）湖南省2011-2019年GDP均值: {hunan_mean}")

2.(7）湖南省2011-2019年GDP均值: 28776.966666666664

<img src=".\image\实验02-4.png" alt="实验02-4" style="zoom:50%;"/>

In [56]:
print('3.')
lending_df = pd.read_csv('./data/Lending.dat', encoding='utf-8')
lending_df['date'] = pd.to_datetime(lending_df['date'])
lending_df

3.

            uid      bid                   title       date
0          7185   344778               有氧健身走与跑入门 2012-10-25
1          7185  1429750                  世界在你心中 2019-02-28
2          7185   229134                    体能训练 2012-02-23
3          7185   441399  欧洲中世纪史:a short history 2016-07-04
4          7185   141446          中国书画名家画语图解.王羲之 2012-10-25
...         ...      ...                     ...        ...
400107  1084420  1625325        格列佛游记:插图·中文导读英文版 2016-03-30
400108    14690    24920                如何做心理学实验 2015-07-10
400109    14690    24920                如何做心理学实验 2016-04-12
400110  1084420   132513                    吕氏春秋 2017-06-28
400111  1084420   386536           希腊神话故事六则:英汉对照 2015-11-15

[400112 rows x 4 columns]

In [57]:
# (1) 查询1084420用户在2016年的借阅情况
print('3.(1) 1084420用户在2016年的借阅情况:')
user_1084420_2016 = lending_df[
    (lending_df['uid'] == 1084420) & 
    (lending_df['date'].dt.year == 2016)
]
user_1084420_2016

3.(1) 1084420用户在2016年的借阅情况:

            uid      bid             title       date
394000  1084420  1324747           罗密欧与朱丽叶 2016-03-23
394007  1084420  1108982          道林·格雷的画像 2016-05-03
394021  1084420  1099307             美丽新世界 2016-05-24
394030  1084420    68856            曹禺戏剧名篇 2016-06-26
394033  1084420  1219131             小人物日记 2016-05-24
...         ...      ...               ...        ...
400080  1084420  1219367             失落的世界 2016-06-26
400096  1084420  1192926              老人与海 2016-05-24
400098  1084420  1160814         幻灭:茅盾小说经典 2016-06-26
400105  1084420   223819          三国演义.第3版 2016-03-11
400107  1084420  1625325  格列佛游记:插图·中文导读英文版 2016-03-30

[77 rows x 4 columns]

In [58]:
# (2) 查询2016、2018和2019年的借阅情况
print('3.(2) 2016、2018和2019年的借阅情况:')
# years_2016_2018_2019 = lending_df[lending_df['date'].str[:4].isin(['2016', '2018', '2019'])]
years_2016_2018_2019 = lending_df[
    lending_df['date'].dt.year.isin([2016, 2018, 2019])
]
years_2016_2018_2019

3.(2) 2016、2018和2019年的借阅情况:

            uid      bid                   title       date
1          7185  1429750                  世界在你心中 2019-02-28
3          7185   441399  欧洲中世纪史:a short history 2016-07-04
32         7185  1110807            汉《曹全碑》隶书技法指南 2018-09-07
33         7185  1080906            世界简史:世界史扛鼎之作 2018-01-24
36         7185  1104260                   家庭断舍离 2018-09-07
...         ...      ...                     ...        ...
400103  1090136  1130413               微观经济学学习指导 2016-03-01
400105  1084420   223819                三国演义.第3版 2016-03-11
400106  1086209    22516                    雾都孤儿 2016-11-18
400107  1084420  1625325        格列佛游记:插图·中文导读英文版 2016-03-30
400109    14690    24920                如何做心理学实验 2016-04-12

[47927 rows x 4 columns]

In [65]:
# (3) 查询借阅了1103310所借图书的用户
print('3.(3) 借阅了1103310所借图书的用户:')
users_borrowed_same = lending_df[
    lending_df['bid'].isin(
        lending_df[lending_df['uid'] == 1103310]['bid']
    ) & 
    (lending_df['uid'] != 1103310)
]

unique_users_sorted = np.sort(users_borrowed_same['uid'].unique())
unique_users_sorted

3.(3) 借阅了1103310所借图书的用户:

array([     13,      14,      19,      24,      51,      72,     224,
           271,     294,     314,     318,     324,     364,     388,
           431,     464,     475,     538,     627,     632,     653,
           660,     704,     708,     732,     760,     798,     848,
           957,     972,     982,     987,    1013,    1073,    1117,
          1137,    1146,    1157,    1180,    1206,    1223,    1284,
          1321,    1375,    1385,    1418,    1420,    1486,    1625,
          1696,    1747,    1763,    1812,    1824,    1888,    1936,
          1937,    2023,    2043,    2078,    2171,    2181,    2198,
          2223,    2275,    2306,    2322,    2365,    2456,    2535,
          2579,    2617,    2684,    2763,    2794,    2799,    2820,
          3037,    3127,    3155,    3170,    3359,    3456,    3471,
          3612,    3701,    3728,    3757,    3797,    3858,    3859,
          3887,    3897,    3935,    4004,    4031,    4045,    4122,
          4223,    4225,    4247,    4301,    4366,    4410,    4429,
          4561,    4672,    4760,    4793,    4822,    4906,    4949,
          5012,    5337,    5414,    5454,    5482,    5562,    5773,
          5938,    6047,    6055,    6068,    6159,    6193,    6432,
          6596,    6869,    6875,    6992,    7328,    7561,    7670,
          7798,    7955,    8025,    8040,    8099,    8288,    8845,
          8904,    8944,    9054,    9196,    9747,   10102,   10551,
         11349,   11682,   11976,   12047,   12356,   12373,   12397,
         12429,   12470,   13367,   13629,   13677,   13802,   13923,
         13967,   14000,   14748,   15000,   15054,   15267,   15293,
         15549,   15661,   15676,   15751,   15865,   15984,   16154,
         16229,   16248,   16329,   17180,   17832,   18054,   18142,
         18535,   18581,   19584,   19665,   19701,   19793,   20024,
         20273,   20289,   20331,   20469,   20677,   20736,   21526,
         21645,   22336,   22492,   22581,   23195,   23459,   24632,
         26070,   27840,   28673,   30659,   31140,   31200,   31702,
         32412,   39856,   40229,   44008,   52319,   64693,   74630,
        114712,  151224,  398636,  398657,  398754,  881106, 1069405,
       1069499, 1083384, 1083503, 1083616, 1083799, 1084110, 1084146,
       1084396, 1084524, 1084534, 1084885, 1085150, 1085162, 1085311,
       1085375, 1086209, 1086980, 1087043, 1087054, 1087184, 1087299,
       1087490, 1087817, 1088183, 1088800, 1088910, 1089272, 1090708,
       1091610, 1102028, 1107147], dtype=int64)